import { Link } from "react-router-dom";
import { Globe2, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useI18n } from "@/contexts/I18nContext";

export default function DataDeletion() {
  const { lang, setLang } = useI18n();
  const isAr = lang === "ar";
  return <div dir={isAr ? "rtl" : "ltr"} className="min-h-screen bg-background text-foreground"><div className="mx-auto max-w-3xl px-6 py-12">
    <header className="mb-10 flex items-start justify-between gap-4 border-b pb-6"><div><div className="mb-3 flex items-center gap-2 text-primary"><Trash2 className="size-5"/><span className="font-semibold">ZMedico</span></div><h1 className="text-3xl font-bold">{isAr ? "حذف البيانات" : "Data Deletion"}</h1><p className="mt-2 text-sm text-muted-foreground">{isAr ? "كيفية طلب حذف بياناتك من ZMedico" : "How to request deletion of your data from ZMedico"}</p></div><Button variant="outline" size="sm" onClick={() => setLang(isAr ? "en" : "ar")}><Globe2 className="me-2 size-4"/>{isAr ? "English" : "العربية"}</Button></header>
    {isAr ? <Arabic/> : <English/>}
    <footer className="mt-12 border-t pt-6 text-sm text-muted-foreground"><div className="flex flex-wrap gap-4"><Link className="hover:underline" to="/trust">{isAr ? "سياسة الخصوصية" : "Privacy Policy"}</Link><Link className="hover:underline" to="/trust?doc=terms">{isAr ? "شروط الاستخدام" : "Terms of Service"}</Link><Link className="hover:underline" to="/">{isAr ? "العودة إلى ZMedico" : "Back to ZMedico"}</Link></div></footer>
  </div></div>;
}
function Arabic(){return <div className="space-y-7 leading-7"><S title="طلب الحذف"><p>إذا كنت تريد طلب حذف بيانات مرتبطة بحسابك أو برسائل أو تكامل مرتبط بـZMedico، تواصل مع مسؤول العيادة أولًا إذا كانت العيادة هي الجهة التي جمعت بياناتك.</p><p>بالنسبة لطلبات الحساب أو بيانات المنصة، تواصل مع إدارة ZMedico من خلال وسيلة الاتصال الرسمية المنشورة على موقع الخدمة، واذكر الاسم ووسيلة التواصل والحساب أو العيادة المرتبطة بالطلب. لا ترسل كلمات المرور أو رموز الوصول.</p></S><S title="ماذا يحدث بعد الطلب"><ul className="list-disc space-y-2 ps-6"><li>نراجع الطلب ونتحقق من صلاحية مقدم الطلب.</li><li>نحدد البيانات المرتبطة بالطلب ونطبق أي متطلبات قانونية للاحتفاظ بها.</li><li>نحذف أو نجعل البيانات غير قابلة للتعريف عندما يكون الحذف مطلوبًا ومسموحًا به.</li><li>قد تحتفظ بعض السجلات المحدودة عندما يكون ذلك ضروريًا للأمن أو منع الاحتيال أو الالتزامات القانونية.</li></ul></S><S title="حذف بيانات Meta والقنوات"><p>إذا تم إرسال بياناتك إلى ZMedico من خلال WhatsApp أو Instagram أو Messenger، فقد تحتاج أيضًا إلى التعامل مع مزود القناة وفق سياساته الخاصة. حذف البيانات من ZMedico لا يعني تلقائيًا حذفها من أنظمة الطرف الثالث.</p></S><S title="المدة"><p>نسعى لمعالجة طلبات الحذف خلال مدة معقولة بعد التحقق من الطلب، مع اختلاف المدة بحسب نطاق الطلب والمتطلبات القانونية والتشغيلية.</p></S><S title="مهم"><p>لا تستخدم هذا النموذج أو الصفحة لإرسال معلومات طبية حساسة أو بيانات اعتماد الحساب. استخدم قناة الاتصال الرسمية فقط.</p></S></div>}
function English(){return <div className="space-y-7 leading-7"><S title="Request Deletion"><p>If you want to request deletion of data associated with your account, messages, or a ZMedico integration, contact the clinic first when the clinic is the organization that collected your information.</p><p>For account or platform data requests, contact ZMedico administration through the official contact method published on the service website. Include your name, contact method, and the account or clinic associated with the request. Do not send passwords or access tokens.</p></S><S title="What Happens Next"><ul className="list-disc space-y-2 ps-6"><li>We review the request and verify the requester's authority.</li><li>We identify the relevant data and apply any legal retention requirements.</li><li>We delete or de-identify information where deletion is required and permitted.</li><li>Limited records may be retained when necessary for security, fraud prevention, or legal obligations.</li></ul></S><S title="Meta and Channel Data"><p>If your information was sent to ZMedico through WhatsApp, Instagram, or Messenger, you may also need to address deletion with the relevant channel provider under its own policies. Deleting data from ZMedico does not automatically delete it from third-party systems.</p></S><S title="Timing"><p>We aim to process deletion requests within a reasonable period after verification. Timing may vary depending on the scope of the request and legal or operational requirements.</p></S><S title="Important"><p>Do not use this page to submit sensitive medical information or account credentials. Use the official contact channel only.</p></S></div>}
function S({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-3"><h2 className="text-xl font-semibold">{title}</h2><div className="space-y-3 text-muted-foreground">{children}</div></section>}
